=== chr33z/Designworkshop-Recipe-Printer/python/recipe-printer-server/recipes/recipeprinter.dtd
<!--

This dtd was originally created by David Horton and taken from
http://www.happy-monkey.net/recipebook/recipebook.dtd.

It is modified to fit our needs. We added the <tag> element to define
categories for each recipe and a <pretimeutc> element to add a time in milliseconds
to the xml (this is for processing reasons only).


Original License:

RecipeXML - An XML recipe markup language.

Copyright (C) 2005 David Horton
This work is licensed under the Creative Commons Attribution Share-Alike
license.  See http://creativecommons.org/licenses/by/2.0/ for details.

-->


<!-- === Hyperlinks for URL references === -->

<!ELEMENT hyperlink (#PCDATA)>
<!ATTLIST hyperlink url CDATA #REQUIRED>


<!-- === Information about a recipe === -->

<!ELEMENT tag (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT blurb (#PCDATA)>
<!ELEMENT effort (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT preptime (#PCDATA)>
<!ELEMENT preptimeutc (#PCDATA)>
<!ELEMENT source (#PCDATA|hyperlink)*>
<!ELEMENT yield (#PCDATA)>


<!-- === Lists of ingredients === -->

<!ELEMENT fooditem (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT unit (#PCDATA)>
<!-- FIXME? The mixed-content definition below does not enforce one and
     only one instance of the tags quantity, unit and fooditem. -->
<!ELEMENT ingredient (#PCDATA | quantity | unit | fooditem)*>


<!-- === Elements of preparation === -->

<!ELEMENT equipment (#PCDATA | hyperlink)*>
<!ELEMENT step (#PCDATA | equipment | hyperlink)*>


<!-- === The main elements of a recipe === -->

<!ELEMENT title (#PCDATA)>
<!ELEMENT recipeinfo (author | blurb | effort | genre | preptime | source | yield | tag | preptimeutc)*>
<!ELEMENT ingredientlist (ingredient)*>
<!ELEMENT preparation (#PCDATA | equipment | step | hyperlink)*>
<!ELEMENT serving (#PCDATA | hyperlink)*>
<!ELEMENT notes (#PCDATA | hyperlink)*>


<!-- === And finally, the recipe itself === -->

<!ELEMENT recipe (title, recipeinfo?, ingredientlist, preparation, serving?, notes?)>


<!-- === The following elements provide logical groupings of recipes === -->


<!-- === A section provides logical divisions of a cookbook === -->

<!ELEMENT section (title, recipe+)>


<!-- === A cookbook consists of one or more recipes or sections === -->

<!ELEMENT cookbook (title, (section | recipe)+)>

=== chr33z/Designworkshop-Recipe-Printer/python/recipe-printer-server/recipes/recipe-pancakes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN" "./recipeprinter.dtd">
<recipe>
  <title>Hippie Pancakes</title>

  <recipeinfo>
    <tag>carbs</tag>
    <blurb>Socially conscious breakfast food.</blurb>

    <author>David Horton</author>

    <yield>12 to 16 small pancakes, enough for two hippies</yield>

    <preptime>10 minutes</preptime>
  </recipeinfo>

  <ingredientlist>
    <ingredient>
      <quantity>100</quantity>
      gr. unbleached wheat blend flour 
    </ingredient>

    <ingredient>
      <quantity>1</quantity>
      tsp. baking powder 
    </ingredient>

    <ingredient>
      <quantity>1</quantity>
      tsp. unrefined sugar 
    </ingredient>

    <ingredient>
      <quantity>1</quantity>
      tsp. coarse kosher salt 
    </ingredient>

    <ingredient>
      <quantity>1</quantity>
      free-range egg
    </ingredient>

    <ingredient>
      <quantity>150</quantity>
      ml. milk 
    </ingredient>

    <ingredient>
      <quantity>1</quantity>
      tsp. organic vegetable oil 
    </ingredient>
  </ingredientlist>

  <preparation>
    Pre-heat griddle over medium heat. Combine dry ingredients in a mixing bowl. Stir in egg, milk and oil. Use a large spoon or gravy ladle to transfer pancake batter to the griddle. Pancakes are ready to flip when large bubbles can be seen on top.
  </preparation>
  <serving>Top with fruit and berries or serve with traditional maple
  syrup.</serving>

  <notes>All-purpose flour may be used instead of wheat blend, but decrease
  the milk by 1/4 C and cut the baking powder by 1/2 tsp. You may also replace
  the unrefined sugar with brown sugar and yes, regular eggs work too, but at
  this point you have completely sold out to The Man and may as well just hop
  in your beemer and drive to some trendy, over-priced, yuppie pancake house
  and get it over with.</notes>
</recipe>

=== chr33z/Designworkshop-Recipe-Printer/python/recipe-printer-server/recipes/recipe-vegetable-lasagne.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN"
"./recipeprinter.dtd">

<!-- Sample recipe in recipebook xml format. be sure to use the right dtd 
	file located at ./recipeprinter.dtd And do not place any xml comments om 
	front of the xml tag! -->

<recipe>
	<title>Vegetable Lasagne</title>

	<recipeinfo>
		<tag>carbs</tag>
		<tag>vegetables</tag>

		<author>Cleidig</author>

		<yield>4 servings</yield>

		<preptime>45 minutes</preptime>
	</recipeinfo>

	<ingredientlist>
		<ingredient>
			<quantity>200</quantity>
			gr. mixed vegetables 
		</ingredient>

		<ingredient>
			<quantity>4</quantity>
			tbs. butter 
		</ingredient>

		<ingredient>
			<quantity>150</quantity>
			ml. milk 
		</ingredient>

		<ingredient>
			<quantity>6</quantity>
			lasagne sheets
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			tbs. flour
		</ingredient>

		<ingredient>
			<quantity>100</quantity>
			gr. gouda cheese 
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			tbs. mixed spices
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			bunch of parsley
		</ingredient>
	</ingredientlist>

	<preparation>
		Butter in einem Topf schmelzen lassen, Mehl einrühren bis es dickflüssig wird, dann die Milch mit einem Schneebesen einrühren. Mit Vegeta, Salz, Pfeffer würzen.
		Das Gemüse schön klein schneiden und in der Soße bissfest ziehen lassen. Zum Schluss Petersilie zugeben.
		Zuerst etwas Soße in eine Auflaufform geben damit der Boden bedeckt ist. Dann abwechselnd Lasagneplatten und Gemüsemischung stapeln. Zum Schluss reichlich mit Käse bedecken und im Backofen bei 200 Grad goldgelb überbacken.
	</preparation>
</recipe>

=== chr33z/Designworkshop-Recipe-Printer/python/recipe-printer-server/recipes/recipe-chili.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN"
"./recipeprinter.dtd">
<recipe>
  <title>30-Minute Chili</title>

  <recipeinfo>
    <blurb>An easy to make, mild chili recipe.</blurb>

    <genre>Soup</genre>

    <author>David Horton</author>

    <preptime>30 minutes</preptime>

    <yield>1 servings</yield>
  </recipeinfo>

  <ingredientlist>
    <ingredient>
      <quantity>1</quantity>
      tsp. olive oil
    </ingredient>

    <ingredient>
      <quantity>1</quantity>
       medium onion, chopped 
     </ingredient>

    <ingredient>
      <quantity>1</quantity>
      cloves garlic, minced 
    </ingredient>

    <ingredient>
      <quantity>100</quantity>
      gr. beef stew meat cut into bite-sized pieces 
    </ingredient>

    <ingredient>
      <quantity>1</quantity>
      tsp. chili powder 
    </ingredient>

    <ingredient>
      <quantity>1</quantity>
      tsp. cumin 
    </ingredient>

    <ingredient>
      <quantity>1</quantity>
      tsp. cayenne pepper 
    </ingredient>

    <ingredient>
      <quantity>8</quantity>
      oz. crushed tomatoes 
    </ingredient>

    <ingredient>
      <quantity>5</quantity>
      oz. Brooks chili hot beans, drained 
    </ingredient>

    <ingredient>
      <quantity>1</quantity>
      tsp. kosher salt 
    </ingredient>

    <ingredient>
      <quantity>1</quantity>
      tsp. brown sugar 
    </ingredient>
  </ingredientlist>

  <preparation>
    Add olive oil, garlic and onion to a 4-quart saucepan. 
    Sweat onion and garlic for a few minutes over medium-low heat. 
    Add beef, chili powder, cumin and cayenne pepper. 
    Raise heat to brown the meat slightly. 
    Add crushed tomatoes, beans, salt and sugar. 
    Reduce heat to a low simmer. 
    Cook for at least 20 minutes before serving, much longer if time permits.
  </preparation>
  <serving>Top with Chihuahua cheese and sour cream. Serve with
  cornbread.</serving>

  <notes>Lean ground beef may be used in place of stew meat.</notes>
</recipe>

=== chr33z/Designworkshop-Recipe-Printer/python/recipe-printer-server/recipes/recipe-stir-fry-chicken.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN" "./recipeprinter.dtd">
<recipe>
	<title>Vegetable Stir Fry with Chicken</title>

	<recipeinfo>
	    <!-- some example tags to use -->
	    <tag>vegetables</tag>
	    <tag>meat</tag>
	    
	    <author>Picassos</author>

		<preptime>About one hour</preptime>
		
		<!-- time in milliseconds is just for processing reasons, so out printer can decide how long the preparation takes -->
		<preptimeutc>1800000</preptimeutc>
	</recipeinfo>

	<ingredientlist>
		<ingredient>
			<quantity>100</quantity>
			gr. chicken breast 
		</ingredient>
		<ingredient>
			<quantity>1</quantity>
			tbs. olive oil 
		</ingredient>

		<ingredient>
			<quantity>100</quantity>
			ml. vegetable stock 
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			medium sized onion 
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			garlic cloves
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			paprica
		</ingredient>

		<ingredient>
			<quantity>75</quantity>
			gr. zucchini 
		</ingredient>

		<ingredient>
			<quantity>500</quantity>
			gr. carrots 
		</ingredient>

		<ingredient>
			<quantity>50</quantity>
			gr. champignions 
		</ingredient>

		<ingredient>
			<quantity>50</quantity>
			gr. sour cream 
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			tbs. creme fraiche 
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			glass red wine 
		</ingredient>
		
		<ingredient>
			<quantity>1</quantity>
			pinch of basil
		</ingredient>
		
		<ingredient>
			<quantity>1</quantity>
			pinch of thyme
		</ingredient>
		
		<ingredient>
			<quantity>1</quantity>
			tbs. italian spices
		</ingredient>
	</ingredientlist>

	<preparation>
		In a 3-quart saucepan sweat garlic and celery in olive oil over medium-low heat. Add ground beef and raise heat to brown slightly. Drain fat if necessary. Add crushed tomatoes, spices, sugar and salt. 
		Lower heat to a slow simmer and add cheese. Cook for at least 30 minutes, much longer if possible. 
	</preparation>

	<serving>Serve over spaghetti or any other favorite pasta.</serving>

	<notes>Make a double batch and freeze the leftover sauce for a quick
		meal
		later on.</notes>
</recipe>

=== chr33z/Designworkshop-Recipe-Printer/python/recipe-printer-server/recipes/recipe-stir-fry.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN" "./recipeprinter.dtd">
<recipe>
	<title>Vegetable Stir Fry</title>

	<recipeinfo>
	    <!-- some example tags to use -->
	    <tag>vegetables</tag>
	    
	    <author>björk</author>

		<yield>Makes enough for 2 portions.</yield>

		<preptime>About one hour</preptime>
		
		<!-- time in milliseconds is just for processing reasons, so out printer can decide how long the preparation takes -->
		<preptimeutc>1500000</preptimeutc>
	</recipeinfo>

	<ingredientlist>
		<ingredient>
			<quantity>1</quantity>
			red onion
		</ingredient>
		
		<ingredient>
			<quantity>1</quantity>
			white onion
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			egg plant
		</ingredient>

		<ingredient>
			<quantity>2</quantity>
			tomatoes
		</ingredient>

		<ingredient>
			<quantity>100</quantity>
			gr. coconut milk 
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			tbs. crushed tomatoes 
		</ingredient>

		<ingredient>
			<quantity>3</quantity>
			tbs. olive oil 
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			piece garlic 
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			tsp. sweet basil
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			pinch of paprica
		</ingredient>
	</ingredientlist>

	<preparation>
		Zwiebeln in grobe Stücke schneiden, Knoblauch fein hacken, Aubergine (und Paprika) in Stücke schneiden und salzen, Tomaten achteln, Kokoscreme in einem Becher heißem Wasser auflösen.
		Zwiebeln und Currypaste in heißem Öl in der Pfanne anbraten. Auberginen dazu, kurz anbraten lassen. Dann die aufgelöste Kokoscreme dazu. Nach einer Weile die Tomaten dazugeben und das ganze gar schmoren lassen. Dazu Reis. 
	</preparation>
</recipe>

=== chr33z/Designworkshop-Recipe-Printer/python/recipe-printer-server/recipes/recipe-lamb-stew.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN"
"./recipeprinter.dtd">
<recipe>
  <title>Lamb Stew</title>

  <recipeinfo>
    <tag>meat</tag>
	<tag>vegetables</tag>
      
    <blurb>An Irish favorite.</blurb>

    <author>David Horton</author>

    <yield>8 servings</yield>
  </recipeinfo>

  <ingredientlist>
    <ingredient><quantity>1</quantity> <unit>tsp.</unit> <fooditem>butter or
    oil</fooditem></ingredient>

    <ingredient><quantity>1</quantity> <fooditem>medium onion</fooditem>,
    diced</ingredient>

    <ingredient><quantity>2</quantity> <unit>cloves</unit>
    <fooditem>garlic</fooditem>, minced</ingredient>

    <ingredient><quantity>8</quantity> <unit>oz.</unit>
    <fooditem>carrots</fooditem>, chopped</ingredient>

    <ingredient><quantity>1</quantity> <unit>lb.</unit> <fooditem>lamb stew
    meat</fooditem>, cut into bite-sized pieces</ingredient>

    <ingredient><quantity>4</quantity> <fooditem>medium red
    potatoes</fooditem></ingredient>

    <ingredient><quantity>16</quantity> <unit>oz.</unit> <fooditem>beef
    broth</fooditem></ingredient>

    <ingredient><quantity>A small handful</quantity> of <fooditem>fresh
    parsley</fooditem>, chopped</ingredient>

    <ingredient><quantity>A few sprigs</quantity> of <fooditem>fresh
    thyme</fooditem></ingredient>

    <ingredient><quantity>A few pinches</quantity> of <fooditem>fresh
    chives</fooditem>, chopped</ingredient>

    <ingredient><quantity>1</quantity> <unit>tsp.</unit>
    <fooditem>cornstarch</fooditem></ingredient>

    <ingredient><quantity>1</quantity> <unit>tsp.</unit> cold
    <fooditem>water</fooditem></ingredient>

    <ingredient><fooditem>Salt and pepper</fooditem> to taste</ingredient>
  </ingredientlist>

  <preparation>Heat butter in a <equipment>3-quart saucepan</equipment>. Add
  onion, garlic and carrots. Sweat vegetables over medium-low heat until onion
  is nearly translucent. Add lamb and raise heat for a few minutes to brown
  the meat slightly. Add broth and reduce heat to low. Add fresh parsley,
  thyme and chives. Peel and cube potatoes while the pot is simmering. Cook
  over low heat until potatoes are tender, about 30 minutes. Mix cornstarch
  and water in a small bowl or cup and add to the stew. Raise the heat
  momentarily so that the corn starch can thicken the stew. Add salt and
  pepper to taste.</preparation>

  <serving>Serve with homemade bread.</serving>

  <notes>For a unique, Irish Pub flavor cut the amount of beef broth in half
  and substitute an equal amount of stout or porter ale.</notes>
</recipe>

=== chr33z/Designworkshop-Recipe-Printer/processing/src/data/recipe-macaroni-and-cheese.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN"
"./recipeprinter.dtd">

<!-- Sample recipe in recipebook xml format. be sure to use the right dtd 
	file located at ./recipeprinter.dtd And do not place any xml comments om 
	front of the xml tag! -->

<recipe>
	<title>Homestyle Macaroni And Cheese</title>

	<recipeinfo>
		<tag>carbs</tag>
		<tag>meat</tag>

		<blurb>Way better than the orange stuff that comes in a box.</blurb>

		<genre>Comfort food</genre>

		<author>David Horton</author>

		<source>
			Loosely based upon a recipe from the
			<hyperlink url="http://www.shermanhospital.com/">Sherman Hospital</hyperlink>
			cafeteria in Elgin, IL
		</source>

		<yield>6 servings</yield>

		<preptime>45 minutes</preptime>
	</recipeinfo>

	<ingredientlist>
		<ingredient>
			<quantity>8</quantity>
			<unit>oz.</unit>
			<fooditem>elbow
				macaroni</fooditem>
		</ingredient>

		<ingredient>
			<quantity>6</quantity>
			<unit>Tbsp.</unit>
			<fooditem>butter</fooditem>
		</ingredient>

		<ingredient>
			<quantity>1/4</quantity>
			<unit>C.</unit>
			<fooditem>flour</fooditem>
		</ingredient>

		<ingredient>
			<quantity>2</quantity>
			<unit>C.</unit>
			<fooditem>milk</fooditem>
		</ingredient>

		<ingredient>
			<quantity>4</quantity>
			<unit>oz.</unit>
			<fooditem>cream
				cheese</fooditem>
		</ingredient>

		<ingredient>
			<quantity>1/2</quantity>
			<unit>tsp.</unit>
			<fooditem>salt</fooditem>
		</ingredient>

		<ingredient>
			<quantity>1/8</quantity>
			<unit>lb.</unit>
			<fooditem>baby Swiss
				cheese slices</fooditem>
		</ingredient>

		<ingredient>
			<quantity>1/4</quantity>
			<unit>lb.</unit>
			<fooditem>colby or
				mild cheddar cheese slices</fooditem>
		</ingredient>
	</ingredientlist>

	<preparation>
		Preheat
		<equipment>oven</equipment>
		to 450 F. Cook macaroni
		until it is almost tender. Drain and rinse thorougly with cold water. Melt
		butter in a
		<equipment>3-quart saucepan</equipment>
		over medium-low heat.
		Slowly add flour, stiring constantly, to make a roux. When roux begins to
		darken in color slowly add the milk and keep stiring even though it
		may feel
		as if your arm will fall off at any minute. Add cream cheese and salt
		stirring until the sauce has a smooth and creamy texture. Fold
		macaroni into
		the sauce. Place 1/3 of the macaroni and sauce mixture into a buttered
		<equipment>8 x 8 inch pan</equipment>
		. Top with a layer of cheddar cheese
		slices. Scoop another 1/3 of the macaroni mixture into the pan. Top with
		baby Swiss slices. Add the remaining macaroni mixture to the pan and top
		with the last of the cheddar slices. Bake at 450 for 15 minutes or
		until top
		begins to brown.
	</preparation>

	<serving>Serve alone or with a thick slice of smoked ham. Refrigerate
		leftovers immediately.</serving>

	<notes>It is very important to avoid aged cheeses as these tend to make
		the
		sauce gritty. Sharp cheddar or Swiss will ruin the texture.</notes>
</recipe>

=== chr33z/Designworkshop-Recipe-Printer/python/recipe-printer-server/recipes/recipe-pickled-jalapeno.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN" "./recipeprinter.dtd">
<recipe>
  <title>Pickled Jalapeno Mix</title>

  <recipeinfo>
    <tag>vegetables</tag>
    <blurb>A zesty south of the border appetizer.</blurb>

    <genre>Mexican food</genre>

    <author>David Horton</author>

    <preptime>30 minutes</preptime>
  </recipeinfo>

  <ingredientlist>
    <ingredient>
      <quantity>4</quantity> 
      Jalapeno peppers, quartered
    </ingredient>
    <ingredient>
      <quantity>4</quantity> 
      oz. Mushrooms, coursely chopped
    </ingredient>
    <ingredient>
      <quantity>1</quantity> 
      Small onion, coursely chopped
    </ingredient>
    <ingredient>
      <quantity>8</quantity> 
      oz. Carrots, sliced
    </ingredient>
    <ingredient>
      <quantity>2</quantity> 
      Bay leaves
    </ingredient>
    <ingredient>
      <quantity>1</quantity> 
      C. Cider vinegar
    </ingredient>
    <ingredient>
      <quantity>1</quantity> 
      C. Water
    </ingredient>
    <ingredient>
      <quantity>1 1/2</quantity> 
      Tbsp. Kosher salt
    </ingredient> 
  </ingredientlist>

  <preparation>
    Combine vinegar, water and salt in a 2-quart saucepan and bring to a boil. Combine jalapenos, mushrooms, onion, carrots and bay leaves in a bowl. Pour hot vinegar solution over peppers and vegetables. Cover and refrigerate.
  </preparation>

  <serving>Serve with tortilla chips as an appetizer.</serving>

  <notes>Leftovers may be kept in the refrigerator for a long time without
  spoilage because of the preserving effects of the vinegar and hot
  peppers.</notes>
</recipe>
