=== chr33z/Designworkshop-Recipe-Printer/python/recipe-printer-server/recipes/recipeprinter.dtd
<!--

This dtd was originally created by David Horton and taken from
http://www.happy-monkey.net/recipebook/recipebook.dtd.

It is modified to fit our needs. We added the <tag> element to define
categories for each recipe and a <pretimeutc> element to add a time in milliseconds
to the xml (this is for processing reasons only).


Original License:

RecipeXML - An XML recipe markup language.

Copyright (C) 2005 David Horton
This work is licensed under the Creative Commons Attribution Share-Alike
license.  See http://creativecommons.org/licenses/by/2.0/ for details.

-->


<!-- === Hyperlinks for URL references === -->

<!ELEMENT hyperlink (#PCDATA)>
<!ATTLIST hyperlink url CDATA #REQUIRED>


<!-- === Information about a recipe === -->

<!ELEMENT tag (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT blurb (#PCDATA)>
<!ELEMENT effort (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT preptime (#PCDATA)>
<!ELEMENT preptimeutc (#PCDATA)>
<!ELEMENT source (#PCDATA|hyperlink)*>
<!ELEMENT yield (#PCDATA)>


<!-- === Lists of ingredients === -->

<!ELEMENT fooditem (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT unit (#PCDATA)>
<!-- FIXME? The mixed-content definition below does not enforce one and
     only one instance of the tags quantity, unit and fooditem. -->
<!ELEMENT ingredient (#PCDATA | quantity | unit | fooditem)*>


<!-- === Elements of preparation === -->

<!ELEMENT equipment (#PCDATA | hyperlink)*>
<!ELEMENT step (#PCDATA | equipment | hyperlink)*>


<!-- === The main elements of a recipe === -->

<!ELEMENT title (#PCDATA)>
<!ELEMENT recipeinfo (author | blurb | effort | genre | preptime | source | yield | tag | preptimeutc)*>
<!ELEMENT ingredientlist (ingredient)*>
<!ELEMENT preparation (#PCDATA | equipment | step | hyperlink)*>
<!ELEMENT serving (#PCDATA | hyperlink)*>
<!ELEMENT notes (#PCDATA | hyperlink)*>


<!-- === And finally, the recipe itself === -->

<!ELEMENT recipe (title, recipeinfo?, ingredientlist, preparation, serving?, notes?)>


<!-- === The following elements provide logical groupings of recipes === -->


<!-- === A section provides logical divisions of a cookbook === -->

<!ELEMENT section (title, recipe+)>


<!-- === A cookbook consists of one or more recipes or sections === -->

<!ELEMENT cookbook (title, (section | recipe)+)>

=== chr33z/Designworkshop-Recipe-Printer/processing/src/data/recipe-stir-fry.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN" "./recipeprinter.dtd">
<recipe>
	<title>Vegetable Stir Fry</title>

	<recipeinfo>
	    <!-- some example tags to use -->
	    <tag>vegetables</tag>
	    
	    <author>björk</author>

		<yield>Makes enough for 2 portions.</yield>

		<preptime>About one hour</preptime>
		
		<!-- time in milliseconds is just for processing reasons, so out printer can decide how long the preparation takes -->
		<preptimeutc>1500000</preptimeutc>
	</recipeinfo>

	<ingredientlist>
		<ingredient>
			<quantity>1</quantity>
			<fooditem>red onion</fooditem>
		</ingredient>
		
		<ingredient>
			<quantity>1</quantity>
			<fooditem>white onion</fooditem>
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			<fooditem>egg plant</fooditem>
		</ingredient>

		<ingredient>
			<quantity>4</quantity>
			<fooditem>tomatoes</fooditem>
		</ingredient>

		<ingredient>
			<quantity>100</quantity>
			<unit>gr.</unit>
			<fooditem>coconut milk</fooditem>
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			<unit>tbs.</unit>
			<fooditem>crushed tomatoes</fooditem>
		</ingredient>

		<ingredient>
			<quantity>3</quantity>
			<unit>tbs.</unit>
			<fooditem>olive oil</fooditem>
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			<unit>piece</unit>
			<fooditem>garlic</fooditem>
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			<unit>tsp.</unit>
			<fooditem>sweet
				basil</fooditem>
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			<fooditem>paprica</fooditem>
		</ingredient>
	</ingredientlist>

	<preparation>
		Zwiebeln in grobe Stücke schneiden, Knoblauch fein hacken, Aubergine (und Paprika) in Stücke schneiden und salzen, Tomaten achteln, Kokoscreme in einem Becher heißem Wasser auflösen.
		Zwiebeln und Currypaste in heißem Öl in der Pfanne anbraten. Auberginen dazu, kurz anbraten lassen. Dann die aufgelöste Kokoscreme dazu. Nach einer Weile die Tomaten dazugeben und das ganze gar schmoren lassen. Dazu Reis. 
	</preparation>
</recipe>
