=== chr33z/Designworkshop-Recipe-Printer/python/recipe-printer-server/recipes/recipeprinter.dtd
<!--

This dtd was originally created by David Horton and taken from
http://www.happy-monkey.net/recipebook/recipebook.dtd.

It is modified to fit our needs. We added the <tag> element to define
categories for each recipe and a <pretimeutc> element to add a time in milliseconds
to the xml (this is for processing reasons only).


Original License:

RecipeXML - An XML recipe markup language.

Copyright (C) 2005 David Horton
This work is licensed under the Creative Commons Attribution Share-Alike
license.  See http://creativecommons.org/licenses/by/2.0/ for details.

-->


<!-- === Hyperlinks for URL references === -->

<!ELEMENT hyperlink (#PCDATA)>
<!ATTLIST hyperlink url CDATA #REQUIRED>


<!-- === Information about a recipe === -->

<!ELEMENT tag (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT blurb (#PCDATA)>
<!ELEMENT effort (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT preptime (#PCDATA)>
<!ELEMENT preptimeutc (#PCDATA)>
<!ELEMENT source (#PCDATA|hyperlink)*>
<!ELEMENT yield (#PCDATA)>


<!-- === Lists of ingredients === -->

<!ELEMENT fooditem (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT unit (#PCDATA)>
<!-- FIXME? The mixed-content definition below does not enforce one and
     only one instance of the tags quantity, unit and fooditem. -->
<!ELEMENT ingredient (#PCDATA | quantity | unit | fooditem)*>


<!-- === Elements of preparation === -->

<!ELEMENT equipment (#PCDATA | hyperlink)*>
<!ELEMENT step (#PCDATA | equipment | hyperlink)*>


<!-- === The main elements of a recipe === -->

<!ELEMENT title (#PCDATA)>
<!ELEMENT recipeinfo (author | blurb | effort | genre | preptime | source | yield | tag | preptimeutc)*>
<!ELEMENT ingredientlist (ingredient)*>
<!ELEMENT preparation (#PCDATA | equipment | step | hyperlink)*>
<!ELEMENT serving (#PCDATA | hyperlink)*>
<!ELEMENT notes (#PCDATA | hyperlink)*>


<!-- === And finally, the recipe itself === -->

<!ELEMENT recipe (title, recipeinfo?, ingredientlist, preparation, serving?, notes?)>


<!-- === The following elements provide logical groupings of recipes === -->


<!-- === A section provides logical divisions of a cookbook === -->

<!ELEMENT section (title, recipe+)>


<!-- === A cookbook consists of one or more recipes or sections === -->

<!ELEMENT cookbook (title, (section | recipe)+)>

=== chr33z/Designworkshop-Recipe-Printer/python/recipe-printer-server/recipes/recipe-bolognese.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN" "./recipeprinter.dtd">
<recipe>
	<title>Pasta Sauce With Meat</title>

	<recipeinfo>
	    <tag>meat</tag>
	    <tag>carbs</tag>
	    
	    <author>I'm the author</author>
		<blurb>A good all-around meat sauce to use with a variety of pasta
			dishes.</blurb>

		<genre>Comfort food</genre>

		<author>David Horton</author>

		<yield>Makes enough for 2 lbs. of pasta.</yield>

		<preptime>About one hour</preptime>
		
		<preptimeutc>60</preptimeutc>
	</recipeinfo>

	<ingredientlist>
		<ingredient>
			<quantity>1</quantity>
			tsp. olive oil 
		</ingredient>
		<ingredient>
			<quantity>1</quantity>
			cloves garlic, minced 
		</ingredient>
		<ingredient>
			<quantity>1</quantity>
			rib celery, finely chopped 
		</ingredient>
		<ingredient>
			<quantity>200</quantity>
			gr. lean ground beef 
		</ingredient>
		<ingredient>
			<quantity>14</quantity>
			oz. crushed tomatoes 
		</ingredient>
		<ingredient>
			<quantity>2</quantity>
			oz. tomato paste 
		</ingredient>
		<ingredient>
			<quantity>1</quantity>
			tsp. Italian seasoning 
		</ingredient>
		<ingredient>
			<quantity>1</quantity>
			tsp. sweet basil 
		</ingredient>
		<ingredient>
			<quantity>1</quantity>
			tsp. brown sugar 
		</ingredient>
		<ingredient>
			<quantity>1</quantity>
			tsp. kosher salt 
		</ingredient>
		<ingredient>
			<quantity>1</quantity>
			pinch of crushed red pepper </ingredient>
		<ingredient>
			<quantity>50</quantity>
			gr. grated Romano cheese 
		</ingredient>
	</ingredientlist>

	<preparation>
		In a 3-quart saucepan sweat garlic and celery in olive oil over medium-low heat. 
		Add ground beef and raise heat to brown slightly. Drain fat if necessary. 
		Add crushed tomatoes, spices, sugar and salt. Lower heat to a slow simmer and add cheese. 
		Cook for at least 30 minutes, much longer if possible. 
	</preparation>

	<serving>Serve over spaghetti or any other favorite pasta.</serving>

	<notes>Make a double batch and freeze the leftover sauce for a quick
		meal
		later on.</notes>
</recipe>

=== chr33z/Designworkshop-Recipe-Printer/processing/src/data/recipe-bolognese.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN" "./recipeprinter.dtd">
<recipe>
	<title>Pasta Sauce With Meat</title>

	<recipeinfo>
	    <!-- some example tags to use -->
	    <tag>meat</tag>
	    <tag>carbs</tag>
	    
	    <author>I'm the author</author>
		<blurb>A good all-around meat sauce to use with a variety of pasta
			dishes.</blurb>

		<genre>Comfort food</genre>

		<author>David Horton</author>

		<yield>Makes enough for 2 lbs. of pasta.</yield>

		<preptime>About one hour</preptime>
		
		<!-- time in milliseconds is just for processing reasons, so out printer can decide how long the preparation takes -->
		<preptimeutc>600000</preptimeutc>
	</recipeinfo>

	<ingredientlist>
		<ingredient>
			<quantity>1</quantity>
			<unit>tsp.</unit>
			<fooditem>olive
				oil</fooditem>
		</ingredient>

		<ingredient>
			<quantity>3</quantity>
			<unit>cloves</unit>
			<fooditem>garlic</fooditem>
			, minced
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			<unit>rib</unit>
			<fooditem>celery</fooditem>
			, finely chopped
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			<unit>lb.</unit>
			<fooditem>lean ground
				beef</fooditem>
		</ingredient>

		<ingredient>
			<quantity>One</quantity>
			<unit>28 oz. can</unit>
			<fooditem>crushed tomatoes</fooditem>
		</ingredient>

		<ingredient>
			<quantity>One</quantity>
			<unit>6 oz. can</unit>
			<fooditem>tomato paste</fooditem>
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			<unit>tsp.</unit>
			<fooditem>Italian
				seasoning</fooditem>
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			<unit>tsp.</unit>
			<fooditem>sweet
				basil</fooditem>
		</ingredient>

		<ingredient>
			<quantity>1 1/2</quantity>
			<unit>tsp.</unit>
			<fooditem>brown
				sugar</fooditem>
		</ingredient>

		<ingredient>
			<quantity>1/2</quantity>
			<unit>tsp.</unit>
			<fooditem>kosher
				salt</fooditem>
		</ingredient>

		<ingredient>
			A
			<quantity>pinch</quantity>
			of
			<fooditem>crushed red
				pepper</fooditem>
		</ingredient>

		<ingredient>
			<quantity>1/4</quantity>
			<unit>C.</unit>
			<fooditem>grated
				Romano cheese</fooditem>
		</ingredient>
	</ingredientlist>

	<preparation>
		In a
		<equipment>3-quart saucepan</equipment>
		sweat garlic and
		celery in olive oil over medium-low heat. Add ground beef and raise heat to
		brown slightly. Drain fat if necessary. Add crushed tomatoes, spices,
		sugar
		and salt. Lower heat to a slow simmer and add cheese. Cook for at least
		30
		minutes, much longer if possible.
	</preparation>

	<serving>Serve over spaghetti or any other favorite pasta.</serving>

	<notes>Make a double batch and freeze the leftover sauce for a quick
		meal
		later on.</notes>
</recipe>

=== chr33z/Designworkshop-Recipe-Printer/python/recipe-printer-server/recipes/recipe-macaroni-and-cheese.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN"
"./recipeprinter.dtd">

<!-- Sample recipe in recipebook xml format. be sure to use the right dtd 
	file located at ./recipeprinter.dtd And do not place any xml comments om 
	front of the xml tag! -->

<recipe>
	<title>Homestyle Macaroni And Cheese</title>

	<recipeinfo>
		<tag>carbs</tag>

		<blurb>Way better than the orange stuff that comes in a box.</blurb>

		<genre>Comfort food</genre>

		<author>David Horton</author>

		<source>
			Loosely based upon a recipe from the
			<hyperlink url="http://www.shermanhospital.com/">Sherman Hospital</hyperlink>
			cafeteria in Elgin, IL
		</source>

		<yield>1 servings</yield>

		<preptime>45 minutes</preptime>
	</recipeinfo>

	<ingredientlist>
		<ingredient>
			<quantity>2</quantity>
			oz. elbow macaroni 
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			Tbsp. butter
		</ingredient>

		<ingredient>
			<quantity>50</quantity>
			gr. flour
		</ingredient>

		<ingredient>
			<quantity>100</quantity>
			ml milk
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			oz. cream cheese 
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			tsp. salt
		</ingredient>

		<ingredient>
			<quantity>50</quantity>
			gr. baby Swiss cheese slices 
		</ingredient>

		<ingredient>
			<quantity>50</quantity>
			gr. colby or mild cheddar cheese slices 
		</ingredient>
	</ingredientlist>

	<preparation>
		Preheat oven to 450 F. 
		Cook macaroni until it is almost tender. Drain and rinse thorougly with cold water. 
		Melt butter in a 3-quart saucepan over medium-low heat. Slowly add flour, stiring constantly, to make a roux. When roux begins to darken in color slowly add the milk and keep stiring even though it may feel as if your arm will fall off at any minute. Add cream cheese and salt stirring until the sauce has a smooth and creamy texture. Fold macaroni into the sauce. 
		Place 1/3 of the macaroni and sauce mixture into a buttered 8 x 8 inch pan. Top with a layer of cheddar cheese slices. Scoop another 1/3 of the macaroni mixture into the pan. Top with baby Swiss slices. Add the remaining macaroni mixture to the pan and top with the last of the cheddar slices. Bake at 450 for 15 minutes or until top begins to brown. 
	</preparation>

	<serving>Serve alone or with a thick slice of smoked ham. Refrigerate
		leftovers immediately.</serving>

	<notes>It is very important to avoid aged cheeses as these tend to make
		the
		sauce gritty. Sharp cheddar or Swiss will ruin the texture.</notes>
</recipe>

=== chr33z/Designworkshop-Recipe-Printer/python/recipe-printer-server/recipes/recipe-asian-fried-noodles-veg-meat.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN"
"./recipeprinter.dtd">

<!-- Sample recipe in recipebook xml format. be sure to use the right dtd 
	file located at ./recipeprinter.dtd And do not place any xml comments om 
	front of the xml tag! -->

<recipe>
	<title>Asian Noodles with Vegetables and Meat</title>

	<recipeinfo>
		<tag>carbs</tag>
		<tag>vegetables</tag>
		<tag>meat</tag>

		<author>Bienchen</author>

		<yield>1 servings</yield>

		<preptime>20 minutes</preptime>
	</recipeinfo>

	<ingredientlist>
		<ingredient>
			<quantity>75</quantity>
			gr.	asian noodles
		</ingredient>

		<ingredient>
			<quantity>2</quantity>
			Tbsp. oil
		</ingredient>

		<ingredient>
			<quantity>75</quantity>
			gr.	pork meat
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			paprica
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			carrots
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			vegetable stock cube
		</ingredient>

		<ingredient>
			<quantity>1</quantity>
			Tbsp. soy sauce
		</ingredient>
	</ingredientlist>

	<preparation>
		Die Nudeln im kochenden Salzwasser nach Packungsaufschrift gar kochen und abseihen.
		Das Fleisch in einer großen Pfanne mit Öl 3 Minuten braten. 
		Die Frühlingszwiebeln putzen, waschen und in 2 cm lange Stücke schneiden. Die Paprikaschote waschen, halbieren, entkernen und in Streifen schneiden. Die Karotten waschen, schälen und grob raspeln oder in dünne Scheiben schneiden.
		Das geschnittene Gemüse zum Fleisch in die Pfanne geben und 2 Minuten mitbraten.
		Brühe, Sojasoße und Stärkemehl in einer Schüssel gut mischen, nach dem Braten zu den übrigen Zutaten in die Pfanne geben und nochmals abschmecken.
		Das Öl in einer anderen Pfanne erhitzen, die abgetropften Nudeln dazugeben und ca. 3 Minuten braten. Danach die Gemüse-Fleischmischung zugeben und vermischen. 
	</preparation>
</recipe>

=== chr33z/Designworkshop-Recipe-Printer/python/recipe-printer-server/recipes/recipe-rigatoni-with-sausage.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN"
"./recipeprinter.dtd">
<recipe>
  <title>Rigatoni with Sausage and Tomato Cream Sauce</title>

  <recipeinfo>
    <tag>meat</tag>
    <tag>carbs</tag>

    <blurb>Tubes of rigatoni hold the tomato sauce, giving you a burst of creamy flavor with every bite.</blurb>

    <genre>Pasta</genre>

    <author>foodandwine.com</author>

    <preptime>30 minutes</preptime>

    <yield>4 servings</yield>
  </recipeinfo>

  <ingredientlist>
    <ingredient>
      <quantity>1</quantity>
      tablespoon olive oil
    </ingredient>
    <ingredient>
      <quantity>250</quantity>
      gr. mild or hot Italian sausage, casings removed
    </ingredient>
    <ingredient>
      <quantity>1</quantity>
      onion, chopped
    </ingredient>
    <ingredient>
      <quantity>1</quantity>
      cloves garlic, minced
    </ingredient>
    <ingredient>
      <quantity>100</quantity>
      ml dry white wine
    </ingredient>
    <ingredient>
      <quantity>200</quantity>
      gr. canned crushed tomatoes
    </ingredient>
    <ingredient>
      <quantity>1</quantity>
      teaspoon salt
    </ingredient>
    <ingredient>
      <quantity>1</quantity>
      teaspoon fresh-ground black pepper
    </ingredient>
    <ingredient>
      <quantity>1</quantity>
      cup chopped fresh parsley
    </ingredient>
    <ingredient>
      <quantity>100</quantity>
      ml light cream
    </ingredient>
    <ingredient>
      <quantity>150</quantity>
      gr. rigatoni
    </ingredient>
    <ingredient>
      <quantity>20</quantity>
      gr. grated Parmesan, for serving
    </ingredient>
  </ingredientlist>

  <preparation>
    In a large frying pan, heat the oil over moderate heat. Add the sausage and cook, breaking up the meat with a fork, until it is no longer pink, about 5 minutes. With a slotted spoon, remove the sausage from the pan. Discard all but 1 tablespoon fat.
    Reduce the heat to moderately low. Add the onion and garlic and cook, stirring occasionally, until the onion is translucent, about 5 minutes. Add the wine and cook until it almost evaporates, about 5 minutes. Stir in the sausage,tomatoes, and salt. Simmer, covered, for 10 minutes. Add the pepper, parsley, and cream.
    In a large pot of boiling, salted water, cook the rigatoni until just done, about 14 minutes. Drain the pasta and toss with the sauce. Serve with grated Parmesan.
  </preparation>

</recipe>

=== chr33z/Designworkshop-Recipe-Printer/python/recipe-printer-server/recipes/recipe-instant-oatmeal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN" "./recipeprinter.dtd">
<recipe>
  <title>Three Bears Instant Oatmeal</title>

  <recipeinfo>
    <tag>carbs</tag>
    <blurb>A quick and easy hot breakfast for cold mornings.</blurb>

    <genre>Breakfast food</genre>

    <author>David Horton</author>

    <yield>12 servings</yield>
  </recipeinfo>

  <ingredientlist>
    <ingredient>
      <quantity>50</quantity> 
      gr. Quick oats
    </ingredient>
    <ingredient>
      <quantity>50</quantity> 
      gr. Powdered milk
    </ingredient>
    <ingredient>
      <quantity>100</quantity> 
      gr. Raisins
    </ingredient>
    <ingredient>
      <quantity>100</quantity> 
      gr. Chopped pecans
    </ingredient>
    <ingredient>
      <quantity>100</quantity> 
      gr. Brown sugar
    </ingredient>
    <ingredient>
      <quantity>1</quantity> 
      tsp. Cinnamon
    </ingredient>
    <ingredient>
      <quantity>1</quantity> 
      tsp. Nutmeg
    </ingredient>
    <ingredient>
      <quantity>1/4</quantity> 
      tsp. Salt
    </ingredient> 
  </ingredientlist>

  <preparation>
    Place all ingredients into a gallon-sized resealable storage bag. Evacuate most of the air from the bag and zip it closed. Gently the shake bag to mix all ingredients taking care to work out any lumps in the brown sugar. 
    To serve, combine 1/2 C instant oatmeal mix with 3/4 C water. Microwave for 2 to 3 minutes. Let cool 1 minute and stir before serving.
  </preparation>

  <notes>Walnuts may be substituted for pecans. You may also want to
  experiment with different types of dried fruits. A combination of
  cranberries and blueberries with walnuts or pecans is very tasty.</notes>
</recipe>

=== chr33z/Designworkshop-Recipe-Printer/python/recipe-printer-server/recipes/recipe-bean-and-ham.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN"
"./recipeprinter.dtd">
<recipe>
    <title>Bean And Ham Soup</title>

    <recipeinfo>
        <tag>meat</tag>
        <tag>vegetables</tag>
        <blurb>A great way to use leftover holiday ham.</blurb>
        <genre>Soup</genre>
        <author>David Horton</author>
        <yield>1 serving</yield>
        <preptime>Five or six hours</preptime>
    </recipeinfo>

    <ingredientlist>
        <ingredient>
            <quantity>50</quantity>
            gr. dry navy beans 
        </ingredient>
        <ingredient>
            <quantity>1</quantity>
            medium onion, diced 
        </ingredient>
        <ingredient>
            <quantity>1</quantity>
            cloves garlic, minced 
        </ingredient>
        <ingredient>
            <quantity>1</quantity>
            ribs celery, chopped 
        </ingredient>
        <ingredient>
            <quantity>1</quantity>
            carrots,sliced 
        </ingredient>
        <ingredient>
            <quantity>1</quantity>
            plum tomatoes, diced 
        </ingredient>
        <ingredient>
            <quantity>50</quantity>
            gr. cooked ham scraps, chopped 
        </ingredient>
        <ingredient>
            <quantity>200</quantity>
            ml water 
        </ingredient>
        <ingredient>
            <quantity>1</quantity>
            ham bone
        </ingredient>
        <ingredient>
            Salt and pepper to taste 
        </ingredient>
    </ingredientlist>
    <preparation>
        Rinse the beans. Combine dry beans and 10 C of water in a 5-quart stockpot and bring to a boil. Remove from heat and let soak for two hours before continuing with the recipe. Use a strainer or colander to drain the water from the beans and set aside. 
        In the stockpot combine ham scraps, garlic, onion, celery and carrot. Sweat vegetables and ham over medium-low heat. There should be enough fat in the ham scraps to keep the veggies from sticking to the pan, but if not add a little vegetable oil. Once the onion becomes translucent add the tomatoes and cook down for a few minutes. When tomatoes are soft add water and stir to create a vegetable broth. 
        Drain and rinse the beans. Add beans and ham bone to the vegetable broth. Simmer over low heat until beans are tender, about 2 to 3 hours. Stir occasionally. After beans are tender add salt and pepper to taste. Do not add salt before this as it can toughen the beans. Discard ham bone and skim off any oil that may be on the surface before serving. 
    </preparation>
    <serving>Serve with rye rolls and apple slices on the side.</serving>
</recipe>

=== chr33z/Designworkshop-Recipe-Printer/python/recipe-printer-server/recipes/recipe-gumbo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN"
"./recipeprinter.dtd">
<recipe>
  <title>Gumbo</title>

  <recipeinfo>
    <tag>meat</tag>
    <tag>vegetables</tag>
      
    <blurb>Warm your tummy with a New Orleans favorite.</blurb>

    <author>David Horton</author>

    <genre>Soups and stews</genre>

    <yield>1 serving</yield>

    <preptime>1 1/2 hours</preptime>
  </recipeinfo>

  <ingredientlist>
    <ingredient>
      <quantity>10</quantity> 
      ml peanut oil
    </ingredient>

    <ingredient>
      <quantity>20</quantity> 
      gr. flour
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      small onion, diced
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      ribs of celery, chopped
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      small green pepper, seeded and diced
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      plum (roma) tomatoes, diced
    </ingredient>

    <ingredient>
      <quantity>100</quantity> 
      gr. okra, sliced
    </ingredient>

    <ingredient>
      <quantity>100</quantity> 
      gr. chicken, cut into bite-sized pieces
    </ingredient>

    <ingredient>
      <quantity>100</quantity> 
      gr. pork cutlet, cut into bite-sized pieces
    </ingredient>

    <ingredient>
      <quantity>100</quantity> 
      gr. wee shrimp, cleaned and de-veined
    </ingredient>

    <ingredient>
      <quantity>200</quantity> 
      ml chicken stock
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      tsp. cayenne pepper
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      tsp. white pepper
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      tsp. black pepper
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      pinch of parsley
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      pinch of sage leaves
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      pinch of thyme leaves
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      pinch of mustard powder
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      whole bay leaf
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      pinch of salt
    </ingredient>

    <ingredient>
      <quantity>100</quantity> 
      gr. parboiled rice
    </ingredient>

    <ingredient>
      <quantity>200</quantity> 
      ml water
    </ingredient>
  </ingredientlist>

  <preparation>
    Create a roux by mixing oil and flour in a 3-quart saucepan over medium heat. Stir often with a wire whisk until the roux becomes the color of peanut butter. Add onion, celery and green pepper. Be very careful as the roux is very hot and tends to splatter when the veggies hit it. 
    Trade the wisk for a large spoon and stir often. When the onion begins to turn translucent add tomatoes and okra. As tomatoes and okra soften add the chicken and pork. The mixture will be very thick at this point, so add a little chicken stock as needed to make stiring less of a chore. 
    When the chicken and pork are slightly browned add the remaining chicken stock and bring to a boil. Stir in all of the spices, cover the pot and reduce heat to a simmer. If the shrimp is frozen add it now otherwise wait until ten minutes before serving. Salt acording to taste. 
    Add the rice to boiling water in a 1-quart saucepan, reduce heat to low and cook for 25 minutes or according to package directions. 
  </preparation>

  <serving>Place a ladle full of gumbo in a bowl and top with a couple
  spoonfuls of rice. Garnish with parsley if you're into the whole
  presentation thing.</serving>

  <notes>When saving leftovers store the gumbo and rice separately at least
  until both are completely cooled, otherwise the rice will get mushy.</notes>
</recipe>
